// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: batch.go

package query

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const updateRowStatus = `-- name: UpdateRowStatus :batchexec
update outbox
set status = $1, updated_at = now()
where id = $2
`

type UpdateRowStatusBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpdateRowStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateRowStatus(ctx context.Context, arg []UpdateRowStatusParams) *UpdateRowStatusBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Status,
			a.ID,
		}
		batch.Queue(updateRowStatus, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpdateRowStatusBatchResults{br, len(arg), false}
}

func (b *UpdateRowStatusBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpdateRowStatusBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
