// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        int64
	UserID    int64
	Status    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type OrderItem struct {
	ID        int64
	OrderID   int64
	Sku       int64
	Quantity  int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Outbox struct {
	ID            int64
	AggregateID   string
	AggregateType string
	EventType     string
	Key           string
	Payload       []byte
	Topic         string
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Stock struct {
	ID         int32
	Sku        int64
	TotalCount int64
	Reserved   int64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
