version: '3'

services:
  loms-db:
    image: gitlab-registry.ozon.dev/go/classroom-16/students/base/postgres:16
    environment:
      POSTGRESQL_USERNAME: loms-user
      POSTGRESQL_PASSWORD: loms-password
      POSTGRESQL_DATABASE: loms_db
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS: 1
      POSTGRESQL_SYNCHRONOUS_COMMIT_MODE: on
    ports:
      - 5432:5432
    volumes:
      - ~/pg/loms_data:/bitnami/postgresql

  loms-db-replica:
    image: gitlab-registry.ozon.dev/go/classroom-16/students/base/postgres:16
    depends_on:
      - loms-db
    environment:
      POSTGRESQL_USERNAME: loms-user
      POSTGRESQL_PASSWORD: loms-password
      POSTGRESQL_PORT_NUMBER: 5433
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_MASTER_HOST: loms-db
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
    ports:
      - 5433:5433

    volumes:
      - ~/pg/loms_data_replica:/bitnami/postgresql