version: '3'

services:
  kafka:
    image: 'bitnami/kafka:4.0'
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CLUSTER_ID: 'c78wwgpuQeG0SQhKc_oTNQ'
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: DOCKER_LIST://:9091,HOST_LIST://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: DOCKER_LIST://kafka:9091,HOST_LIST://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_LIST:PLAINTEXT,HOST_LIST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: DOCKER_LIST

    volumes:
      - ~/route_kafka/kafka_1:/bitnami/kafka

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    depends_on:
      - kafka
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: 'route-kafka'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9091
      DYNAMIC_CONFIG_ENABLED: 'true'

  bootstrap-kafka:
    image: 'bitnami/kafka:4.0'
    depends_on:
      - kafka
    command: 'kafka-topics.sh --topic loms.order-events --create --if-not-exists --partitions 2 --replication-factor 1 --bootstrap-server kafka:9091'