app:
  edit_interval: 1s

service:
  host: localhost
  grpc_port: 8085
  http_port: 8086

db_shards:
  - host: "postgres-comments-shard-1"
    port: 5432
    user: comments-user-1
    password: comments-password-1
    db_name: comments_db

  - host: "postgres-comments-shard-2"
    port: 5432
    user: comments-user-2
    password: comments-password-2
    db_name: comments_db
