// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: stocks/v1/stocks.proto

package stocks_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StocksService_StocksInfo_FullMethodName = "/stocks.v1.StocksService/StocksInfo"
)

// StocksServiceClient is the client API for StocksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StocksServiceClient interface {
	StocksInfo(ctx context.Context, in *StocksInfoRequest, opts ...grpc.CallOption) (*StocksInfoResponse, error)
}

type stocksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStocksServiceClient(cc grpc.ClientConnInterface) StocksServiceClient {
	return &stocksServiceClient{cc}
}

func (c *stocksServiceClient) StocksInfo(ctx context.Context, in *StocksInfoRequest, opts ...grpc.CallOption) (*StocksInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StocksInfoResponse)
	err := c.cc.Invoke(ctx, StocksService_StocksInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StocksServiceServer is the server API for StocksService service.
// All implementations must embed UnimplementedStocksServiceServer
// for forward compatibility.
type StocksServiceServer interface {
	StocksInfo(context.Context, *StocksInfoRequest) (*StocksInfoResponse, error)
	mustEmbedUnimplementedStocksServiceServer()
}

// UnimplementedStocksServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStocksServiceServer struct{}

func (UnimplementedStocksServiceServer) StocksInfo(context.Context, *StocksInfoRequest) (*StocksInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StocksInfo not implemented")
}
func (UnimplementedStocksServiceServer) mustEmbedUnimplementedStocksServiceServer() {}
func (UnimplementedStocksServiceServer) testEmbeddedByValue()                       {}

// UnsafeStocksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StocksServiceServer will
// result in compilation errors.
type UnsafeStocksServiceServer interface {
	mustEmbedUnimplementedStocksServiceServer()
}

func RegisterStocksServiceServer(s grpc.ServiceRegistrar, srv StocksServiceServer) {
	// If the following call pancis, it indicates UnimplementedStocksServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StocksService_ServiceDesc, srv)
}

func _StocksService_StocksInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StocksInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StocksServiceServer).StocksInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StocksService_StocksInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StocksServiceServer).StocksInfo(ctx, req.(*StocksInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StocksService_ServiceDesc is the grpc.ServiceDesc for StocksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StocksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stocks.v1.StocksService",
	HandlerType: (*StocksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StocksInfo",
			Handler:    _StocksService_StocksInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stocks/v1/stocks.proto",
}
