// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package service_test

//go:generate minimock -i route256/cart/internal/domain/cart/service.StocksClient -o stocks_client_mock_test.go -n StocksClientMock -p service_test

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// StocksClientMock implements StocksClient
type StocksClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcStockInfo          func(ctx context.Context, skuId int64) (u1 uint32, err error)
	funcStockInfoOrigin    string
	inspectFuncStockInfo   func(ctx context.Context, skuId int64)
	afterStockInfoCounter  uint64
	beforeStockInfoCounter uint64
	StockInfoMock          mStocksClientMockStockInfo
}

// NewStocksClientMock returns a mock for StocksClient
func NewStocksClientMock(t minimock.Tester) *StocksClientMock {
	m := &StocksClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.StockInfoMock = mStocksClientMockStockInfo{mock: m}
	m.StockInfoMock.callArgs = []*StocksClientMockStockInfoParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStocksClientMockStockInfo struct {
	optional           bool
	mock               *StocksClientMock
	defaultExpectation *StocksClientMockStockInfoExpectation
	expectations       []*StocksClientMockStockInfoExpectation

	callArgs []*StocksClientMockStockInfoParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StocksClientMockStockInfoExpectation specifies expectation struct of the StocksClient.StockInfo
type StocksClientMockStockInfoExpectation struct {
	mock               *StocksClientMock
	params             *StocksClientMockStockInfoParams
	paramPtrs          *StocksClientMockStockInfoParamPtrs
	expectationOrigins StocksClientMockStockInfoExpectationOrigins
	results            *StocksClientMockStockInfoResults
	returnOrigin       string
	Counter            uint64
}

// StocksClientMockStockInfoParams contains parameters of the StocksClient.StockInfo
type StocksClientMockStockInfoParams struct {
	ctx   context.Context
	skuId int64
}

// StocksClientMockStockInfoParamPtrs contains pointers to parameters of the StocksClient.StockInfo
type StocksClientMockStockInfoParamPtrs struct {
	ctx   *context.Context
	skuId *int64
}

// StocksClientMockStockInfoResults contains results of the StocksClient.StockInfo
type StocksClientMockStockInfoResults struct {
	u1  uint32
	err error
}

// StocksClientMockStockInfoOrigins contains origins of expectations of the StocksClient.StockInfo
type StocksClientMockStockInfoExpectationOrigins struct {
	origin      string
	originCtx   string
	originSkuId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmStockInfo *mStocksClientMockStockInfo) Optional() *mStocksClientMockStockInfo {
	mmStockInfo.optional = true
	return mmStockInfo
}

// Expect sets up expected params for StocksClient.StockInfo
func (mmStockInfo *mStocksClientMockStockInfo) Expect(ctx context.Context, skuId int64) *mStocksClientMockStockInfo {
	if mmStockInfo.mock.funcStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("StocksClientMock.StockInfo mock is already set by Set")
	}

	if mmStockInfo.defaultExpectation == nil {
		mmStockInfo.defaultExpectation = &StocksClientMockStockInfoExpectation{}
	}

	if mmStockInfo.defaultExpectation.paramPtrs != nil {
		mmStockInfo.mock.t.Fatalf("StocksClientMock.StockInfo mock is already set by ExpectParams functions")
	}

	mmStockInfo.defaultExpectation.params = &StocksClientMockStockInfoParams{ctx, skuId}
	mmStockInfo.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmStockInfo.expectations {
		if minimock.Equal(e.params, mmStockInfo.defaultExpectation.params) {
			mmStockInfo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStockInfo.defaultExpectation.params)
		}
	}

	return mmStockInfo
}

// ExpectCtxParam1 sets up expected param ctx for StocksClient.StockInfo
func (mmStockInfo *mStocksClientMockStockInfo) ExpectCtxParam1(ctx context.Context) *mStocksClientMockStockInfo {
	if mmStockInfo.mock.funcStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("StocksClientMock.StockInfo mock is already set by Set")
	}

	if mmStockInfo.defaultExpectation == nil {
		mmStockInfo.defaultExpectation = &StocksClientMockStockInfoExpectation{}
	}

	if mmStockInfo.defaultExpectation.params != nil {
		mmStockInfo.mock.t.Fatalf("StocksClientMock.StockInfo mock is already set by Expect")
	}

	if mmStockInfo.defaultExpectation.paramPtrs == nil {
		mmStockInfo.defaultExpectation.paramPtrs = &StocksClientMockStockInfoParamPtrs{}
	}
	mmStockInfo.defaultExpectation.paramPtrs.ctx = &ctx
	mmStockInfo.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmStockInfo
}

// ExpectSkuIdParam2 sets up expected param skuId for StocksClient.StockInfo
func (mmStockInfo *mStocksClientMockStockInfo) ExpectSkuIdParam2(skuId int64) *mStocksClientMockStockInfo {
	if mmStockInfo.mock.funcStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("StocksClientMock.StockInfo mock is already set by Set")
	}

	if mmStockInfo.defaultExpectation == nil {
		mmStockInfo.defaultExpectation = &StocksClientMockStockInfoExpectation{}
	}

	if mmStockInfo.defaultExpectation.params != nil {
		mmStockInfo.mock.t.Fatalf("StocksClientMock.StockInfo mock is already set by Expect")
	}

	if mmStockInfo.defaultExpectation.paramPtrs == nil {
		mmStockInfo.defaultExpectation.paramPtrs = &StocksClientMockStockInfoParamPtrs{}
	}
	mmStockInfo.defaultExpectation.paramPtrs.skuId = &skuId
	mmStockInfo.defaultExpectation.expectationOrigins.originSkuId = minimock.CallerInfo(1)

	return mmStockInfo
}

// Inspect accepts an inspector function that has same arguments as the StocksClient.StockInfo
func (mmStockInfo *mStocksClientMockStockInfo) Inspect(f func(ctx context.Context, skuId int64)) *mStocksClientMockStockInfo {
	if mmStockInfo.mock.inspectFuncStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("Inspect function is already set for StocksClientMock.StockInfo")
	}

	mmStockInfo.mock.inspectFuncStockInfo = f

	return mmStockInfo
}

// Return sets up results that will be returned by StocksClient.StockInfo
func (mmStockInfo *mStocksClientMockStockInfo) Return(u1 uint32, err error) *StocksClientMock {
	if mmStockInfo.mock.funcStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("StocksClientMock.StockInfo mock is already set by Set")
	}

	if mmStockInfo.defaultExpectation == nil {
		mmStockInfo.defaultExpectation = &StocksClientMockStockInfoExpectation{mock: mmStockInfo.mock}
	}
	mmStockInfo.defaultExpectation.results = &StocksClientMockStockInfoResults{u1, err}
	mmStockInfo.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmStockInfo.mock
}

// Set uses given function f to mock the StocksClient.StockInfo method
func (mmStockInfo *mStocksClientMockStockInfo) Set(f func(ctx context.Context, skuId int64) (u1 uint32, err error)) *StocksClientMock {
	if mmStockInfo.defaultExpectation != nil {
		mmStockInfo.mock.t.Fatalf("Default expectation is already set for the StocksClient.StockInfo method")
	}

	if len(mmStockInfo.expectations) > 0 {
		mmStockInfo.mock.t.Fatalf("Some expectations are already set for the StocksClient.StockInfo method")
	}

	mmStockInfo.mock.funcStockInfo = f
	mmStockInfo.mock.funcStockInfoOrigin = minimock.CallerInfo(1)
	return mmStockInfo.mock
}

// When sets expectation for the StocksClient.StockInfo which will trigger the result defined by the following
// Then helper
func (mmStockInfo *mStocksClientMockStockInfo) When(ctx context.Context, skuId int64) *StocksClientMockStockInfoExpectation {
	if mmStockInfo.mock.funcStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("StocksClientMock.StockInfo mock is already set by Set")
	}

	expectation := &StocksClientMockStockInfoExpectation{
		mock:               mmStockInfo.mock,
		params:             &StocksClientMockStockInfoParams{ctx, skuId},
		expectationOrigins: StocksClientMockStockInfoExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmStockInfo.expectations = append(mmStockInfo.expectations, expectation)
	return expectation
}

// Then sets up StocksClient.StockInfo return parameters for the expectation previously defined by the When method
func (e *StocksClientMockStockInfoExpectation) Then(u1 uint32, err error) *StocksClientMock {
	e.results = &StocksClientMockStockInfoResults{u1, err}
	return e.mock
}

// Times sets number of times StocksClient.StockInfo should be invoked
func (mmStockInfo *mStocksClientMockStockInfo) Times(n uint64) *mStocksClientMockStockInfo {
	if n == 0 {
		mmStockInfo.mock.t.Fatalf("Times of StocksClientMock.StockInfo mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmStockInfo.expectedInvocations, n)
	mmStockInfo.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmStockInfo
}

func (mmStockInfo *mStocksClientMockStockInfo) invocationsDone() bool {
	if len(mmStockInfo.expectations) == 0 && mmStockInfo.defaultExpectation == nil && mmStockInfo.mock.funcStockInfo == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmStockInfo.mock.afterStockInfoCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmStockInfo.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// StockInfo implements StocksClient
func (mmStockInfo *StocksClientMock) StockInfo(ctx context.Context, skuId int64) (u1 uint32, err error) {
	mm_atomic.AddUint64(&mmStockInfo.beforeStockInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmStockInfo.afterStockInfoCounter, 1)

	mmStockInfo.t.Helper()

	if mmStockInfo.inspectFuncStockInfo != nil {
		mmStockInfo.inspectFuncStockInfo(ctx, skuId)
	}

	mm_params := StocksClientMockStockInfoParams{ctx, skuId}

	// Record call args
	mmStockInfo.StockInfoMock.mutex.Lock()
	mmStockInfo.StockInfoMock.callArgs = append(mmStockInfo.StockInfoMock.callArgs, &mm_params)
	mmStockInfo.StockInfoMock.mutex.Unlock()

	for _, e := range mmStockInfo.StockInfoMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmStockInfo.StockInfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStockInfo.StockInfoMock.defaultExpectation.Counter, 1)
		mm_want := mmStockInfo.StockInfoMock.defaultExpectation.params
		mm_want_ptrs := mmStockInfo.StockInfoMock.defaultExpectation.paramPtrs

		mm_got := StocksClientMockStockInfoParams{ctx, skuId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmStockInfo.t.Errorf("StocksClientMock.StockInfo got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStockInfo.StockInfoMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.skuId != nil && !minimock.Equal(*mm_want_ptrs.skuId, mm_got.skuId) {
				mmStockInfo.t.Errorf("StocksClientMock.StockInfo got unexpected parameter skuId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStockInfo.StockInfoMock.defaultExpectation.expectationOrigins.originSkuId, *mm_want_ptrs.skuId, mm_got.skuId, minimock.Diff(*mm_want_ptrs.skuId, mm_got.skuId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStockInfo.t.Errorf("StocksClientMock.StockInfo got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmStockInfo.StockInfoMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStockInfo.StockInfoMock.defaultExpectation.results
		if mm_results == nil {
			mmStockInfo.t.Fatal("No results are set for the StocksClientMock.StockInfo")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmStockInfo.funcStockInfo != nil {
		return mmStockInfo.funcStockInfo(ctx, skuId)
	}
	mmStockInfo.t.Fatalf("Unexpected call to StocksClientMock.StockInfo. %v %v", ctx, skuId)
	return
}

// StockInfoAfterCounter returns a count of finished StocksClientMock.StockInfo invocations
func (mmStockInfo *StocksClientMock) StockInfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStockInfo.afterStockInfoCounter)
}

// StockInfoBeforeCounter returns a count of StocksClientMock.StockInfo invocations
func (mmStockInfo *StocksClientMock) StockInfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStockInfo.beforeStockInfoCounter)
}

// Calls returns a list of arguments used in each call to StocksClientMock.StockInfo.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStockInfo *mStocksClientMockStockInfo) Calls() []*StocksClientMockStockInfoParams {
	mmStockInfo.mutex.RLock()

	argCopy := make([]*StocksClientMockStockInfoParams, len(mmStockInfo.callArgs))
	copy(argCopy, mmStockInfo.callArgs)

	mmStockInfo.mutex.RUnlock()

	return argCopy
}

// MinimockStockInfoDone returns true if the count of the StockInfo invocations corresponds
// the number of defined expectations
func (m *StocksClientMock) MinimockStockInfoDone() bool {
	if m.StockInfoMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.StockInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.StockInfoMock.invocationsDone()
}

// MinimockStockInfoInspect logs each unmet expectation
func (m *StocksClientMock) MinimockStockInfoInspect() {
	for _, e := range m.StockInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StocksClientMock.StockInfo at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterStockInfoCounter := mm_atomic.LoadUint64(&m.afterStockInfoCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.StockInfoMock.defaultExpectation != nil && afterStockInfoCounter < 1 {
		if m.StockInfoMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StocksClientMock.StockInfo at\n%s", m.StockInfoMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StocksClientMock.StockInfo at\n%s with params: %#v", m.StockInfoMock.defaultExpectation.expectationOrigins.origin, *m.StockInfoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStockInfo != nil && afterStockInfoCounter < 1 {
		m.t.Errorf("Expected call to StocksClientMock.StockInfo at\n%s", m.funcStockInfoOrigin)
	}

	if !m.StockInfoMock.invocationsDone() && afterStockInfoCounter > 0 {
		m.t.Errorf("Expected %d calls to StocksClientMock.StockInfo at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.StockInfoMock.expectedInvocations), m.StockInfoMock.expectedInvocationsOrigin, afterStockInfoCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StocksClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockStockInfoInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StocksClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StocksClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockStockInfoDone()
}
